### PR TITLE
Added a http request content type checker

### PR DESCRIPTION
**Pull request by aidanhl**
Accepts list of allowed http request content type, and will only allow
those types to pass.

### CODE REVIEW

**Comment by aidanhl** [comment]
@mirthy @vdaron Any modifications that should be made?

**Comment by vdaron** [comment]
Thanks for the pull request @aidanhl

**Comment by aidanhl** [comment]
Awesome! Very glad to have it merged in :)

**Comment by mirthy** [comment]
Published out to nuget and Github

**Pull request merged**
